### ISSUE TITLE
Clarification on "Startup Settings" mentioned in the alarm_en.md

### ISSUE THREAD

**Issue by piotr-zemla** [Scirese/alarm#3]
This may be a dumb question, sorry for the inconvenience.

The document links straight to [ophub/amlogic-s9xxx-armbian](https://github.com/ophub/amlogic-s9xxx-armbian/), but I was unable to find anything important there concerning "Startup Settings" that would be applicable.

A more precise link would be greatly appreciated.

**Comment by Scirese** [comment]
Thanks your feedback.
For this, It's my misconsideration to not aware that English documents in [ophub/amlogic-s9xxx-armbian](https://github.com/ophub/amlogic-s9xxx-armbian/) are poorly written. So I didn't mention more in my docs XD.

And I have to say the method mentioned in my document are quite stupid and unstandard(Just some thoughts suddenly come up with). Now we already have a standard prebuilt image in (7Ji/amlogic-s9xxx-archlinuxarm)[https://github.com/7Ji/amlogic-s9xxx-archlinuxarm] and you dont need to go through the section anymore.

My docs will probably be rewritten and change its focus on the expirence guide(eg. tips and tricks).
